
package framework.integrations.gwServices.maintenanceToolsAPI.pc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-05-03T11:46:38.317-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "IllegalArgumentException", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc1000/MaintenanceToolsAPI")
public class IllegalArgumentException_Exception extends Exception {

    private framework.integrations.gwServices.maintenanceToolsAPI.pc.IllegalArgumentException illegalArgumentException;

    public IllegalArgumentException_Exception() {
        super();
    }

    public IllegalArgumentException_Exception(String message) {
        super(message);
    }

    public IllegalArgumentException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IllegalArgumentException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.pc.IllegalArgumentException illegalArgumentException) {
        super(message);
        this.illegalArgumentException = illegalArgumentException;
    }

    public IllegalArgumentException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.pc.IllegalArgumentException illegalArgumentException, java.lang.Throwable cause) {
        super(message, cause);
        this.illegalArgumentException = illegalArgumentException;
    }

    public framework.integrations.gwServices.maintenanceToolsAPI.pc.IllegalArgumentException getFaultInfo() {
        return this.illegalArgumentException;
    }
}
