
package framework.integrations.gwServices.gwTestRunner.com.waysysweb;

import framework.integrations.gwServices.gwTestRunner.com.example.unittestcase.TestCaseResult;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RunTestPortType", targetNamespace = "http://waysysweb.com")
@XmlSeeAlso({
        framework.integrations.gwServices.gwTestRunner.com.waysysweb.ObjectFactory.class,
        framework.integrations.gwServices.gwTestRunner.com.example.unittestcase.ObjectFactory.class,
        framework.integrations.gwServices.gwTestRunner.com.guidewire.ws.soapheaders.ObjectFactory.class,
        framework.integrations.gwServices.gwTestRunner.generated.ObjectFactory.class
})
public interface RunTestPortType {


    /**
     * 
     * @param reportName
     * @param testName
     * @return
     *     returns com.example.unittestcase.TestCaseResult
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://waysysweb.com")
    @RequestWrapper(localName = "runTest", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.RunTest")
    @ResponseWrapper(localName = "runTestResponse", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.RunTestResponse")
    public TestCaseResult runTest(
        @WebParam(name = "testName", targetNamespace = "http://waysysweb.com")
        String testName,
        @WebParam(name = "reportName", targetNamespace = "http://waysysweb.com")
        String reportName)
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param testName
     * @return
     *     returns com.waysysweb.RunTestAsJUnitResponse.Return
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://waysysweb.com")
    @RequestWrapper(localName = "runTestAsJUnit", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.RunTestAsJUnit")
    @ResponseWrapper(localName = "runTestAsJUnitResponse", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.RunTestAsJUnitResponse")
    public RunTestAsJUnitResponse.Return runTestAsJUnit(
        @WebParam(name = "testName", targetNamespace = "http://waysysweb.com")
        String testName)
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param tests
     * @param packageStr
     * @param suiteName
     * @return
     *     returns com.waysysweb.RunGeneratedPackageSuiteAsJUnitResponse.Return
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://waysysweb.com")
    @RequestWrapper(localName = "runGeneratedPackageSuiteAsJUnit", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.RunGeneratedPackageSuiteAsJUnit")
    @ResponseWrapper(localName = "runGeneratedPackageSuiteAsJUnitResponse", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.RunGeneratedPackageSuiteAsJUnitResponse")
    public RunGeneratedPackageSuiteAsJUnitResponse.Return runGeneratedPackageSuiteAsJUnit(
        @WebParam(name = "suiteName", targetNamespace = "http://waysysweb.com")
        String suiteName,
        @WebParam(name = "tests", targetNamespace = "http://waysysweb.com")
        RunGeneratedPackageSuiteAsJUnit.Tests tests,
        @WebParam(name = "packageStr", targetNamespace = "http://waysysweb.com")
        String packageStr)
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param fileName
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.DeleteResponse")
    public void delete(
        @WebParam(name = "fileName", targetNamespace = "http://waysysweb.com")
        String fileName)
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param testName
     * @return
     *     returns java.lang.String
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://waysysweb.com")
    @RequestWrapper(localName = "createInitialMessage", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.CreateInitialMessage")
    @ResponseWrapper(localName = "createInitialMessageResponse", targetNamespace = "http://waysysweb.com", className = "com.waysysweb.CreateInitialMessageResponse")
    public String createInitialMessage(
        @WebParam(name = "testName", targetNamespace = "http://waysysweb.com")
        String testName)
        throws WsiAuthenticationException_Exception
    ;

}
