
package framework.integrations.gwServices.debugToolsAPI.bc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-05-24T12:55:28.404-06:00
 * Generated source version: 3.4.3
 *
 */
public final class BCDebugToolsAPIPortType_BCDebugToolsAPISoap12Port_Client {

    private static final QName SERVICE_NAME = new QName("http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", "BCDebugToolsAPI");

    private BCDebugToolsAPIPortType_BCDebugToolsAPISoap12Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BCDebugToolsAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BCDebugToolsAPI ss = new BCDebugToolsAPI(wsdlURL, SERVICE_NAME);
        BCDebugToolsAPIPortType port = ss.getBCDebugToolsAPISoap12Port();

        {
        System.out.println("Invoking moveClockTo...");
        javax.xml.datatype.XMLGregorianCalendar _moveClockTo_date = null;
        try {
            port.moveClockTo(_moveClockTo_date);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runInvoice...");
        try {
            port.runInvoice();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runReceivableAging...");
        try {
            port.runReceivableAging();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isInvoiceRunning...");
        try {
            java.lang.Boolean _isInvoiceRunning__return = port.isInvoiceRunning();
            System.out.println("isInvoiceRunning.result=" + _isInvoiceRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isPaymentRequestRunning...");
        try {
            java.lang.Boolean _isPaymentRequestRunning__return = port.isPaymentRequestRunning();
            System.out.println("isPaymentRequestRunning.result=" + _isPaymentRequestRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runWorkflow...");
        try {
            port.runWorkflow();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isCaptureDailyBalancesRunning...");
        try {
            java.lang.Boolean _isCaptureDailyBalancesRunning__return = port.isCaptureDailyBalancesRunning();
            System.out.println("isCaptureDailyBalancesRunning.result=" + _isCaptureDailyBalancesRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runPaymentRequest...");
        try {
            port.runPaymentRequest();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runInvoiceDue...");
        try {
            port.runInvoiceDue();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isInvoiceDueRunning...");
        try {
            java.lang.Boolean _isInvoiceDueRunning__return = port.isInvoiceDueRunning();
            System.out.println("isInvoiceDueRunning.result=" + _isInvoiceDueRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isReceivableAgingRunning...");
        try {
            java.lang.Boolean _isReceivableAgingRunning__return = port.isReceivableAgingRunning();
            System.out.println("isReceivableAgingRunning.result=" + _isReceivableAgingRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getCurrentDate...");
        try {
            javax.xml.datatype.XMLGregorianCalendar _getCurrentDate__return = port.getCurrentDate();
            System.out.println("getCurrentDate.result=" + _getCurrentDate__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isWorkflowRunning...");
        try {
            java.lang.Boolean _isWorkflowRunning__return = port.isWorkflowRunning();
            System.out.println("isWorkflowRunning.result=" + _isWorkflowRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runCaptureDailyBalances...");
        try {
            port.runCaptureDailyBalances();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
