
package framework.integrations.gwServices.debugToolsAPI.bc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BCDebugToolsAPIPortType", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BCDebugToolsAPIPortType {


    /**
     * 
     * @param date
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "moveClockTo", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.MoveClockTo")
    @ResponseWrapper(localName = "moveClockToResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.MoveClockToResponse")
    public void moveClockTo(
        @WebParam(name = "date", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
        XMLGregorianCalendar date)
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
    @RequestWrapper(localName = "getCurrentDate", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.GetCurrentDate")
    @ResponseWrapper(localName = "getCurrentDateResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.GetCurrentDateResponse")
    public XMLGregorianCalendar getCurrentDate()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runInvoice", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunInvoice")
    @ResponseWrapper(localName = "runInvoiceResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunInvoiceResponse")
    public void runInvoice()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
    @RequestWrapper(localName = "isInvoiceRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsInvoiceRunning")
    @ResponseWrapper(localName = "isInvoiceRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsInvoiceRunningResponse")
    public Boolean isInvoiceRunning()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runInvoiceDue", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunInvoiceDue")
    @ResponseWrapper(localName = "runInvoiceDueResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunInvoiceDueResponse")
    public void runInvoiceDue()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
    @RequestWrapper(localName = "isInvoiceDueRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsInvoiceDueRunning")
    @ResponseWrapper(localName = "isInvoiceDueRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsInvoiceDueRunningResponse")
    public Boolean isInvoiceDueRunning()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runPaymentRequest", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunPaymentRequest")
    @ResponseWrapper(localName = "runPaymentRequestResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunPaymentRequestResponse")
    public void runPaymentRequest()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
    @RequestWrapper(localName = "isPaymentRequestRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsPaymentRequestRunning")
    @ResponseWrapper(localName = "isPaymentRequestRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsPaymentRequestRunningResponse")
    public Boolean isPaymentRequestRunning()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runWorkflow", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunWorkflow")
    @ResponseWrapper(localName = "runWorkflowResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunWorkflowResponse")
    public void runWorkflow()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
    @RequestWrapper(localName = "isWorkflowRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsWorkflowRunning")
    @ResponseWrapper(localName = "isWorkflowRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsWorkflowRunningResponse")
    public Boolean isWorkflowRunning()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runReceivableAging", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunReceivableAging")
    @ResponseWrapper(localName = "runReceivableAgingResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunReceivableAgingResponse")
    public void runReceivableAging()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
    @RequestWrapper(localName = "isReceivableAgingRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsReceivableAgingRunning")
    @ResponseWrapper(localName = "isReceivableAgingRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsReceivableAgingRunningResponse")
    public Boolean isReceivableAgingRunning()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runCaptureDailyBalances", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunCaptureDailyBalances")
    @ResponseWrapper(localName = "runCaptureDailyBalancesResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.RunCaptureDailyBalancesResponse")
    public void runCaptureDailyBalances()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI")
    @RequestWrapper(localName = "isCaptureDailyBalancesRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsCaptureDailyBalancesRunning")
    @ResponseWrapper(localName = "isCaptureDailyBalancesRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc801/BCDebugToolsAPI", className = "gwclockservice.bcdebugtoolsapi.IsCaptureDailyBalancesRunningResponse")
    public Boolean isCaptureDailyBalancesRunning()
        throws WsiAuthenticationException_Exception
    ;

}
