package framework.integrations.gwServices.debugToolsAPI.bc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-05-24T12:55:28.458-06:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", name = "BCDebugToolsAPIPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BCDebugToolsAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "moveClockTo", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.MoveClockTo")
    @ResponseWrapper(localName = "moveClockToResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.MoveClockToResponse")
    public void moveClockTo(

        @WebParam(name = "date", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
        javax.xml.datatype.XMLGregorianCalendar date
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runInvoice", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunInvoice")
    @ResponseWrapper(localName = "runInvoiceResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunInvoiceResponse")
    public void runInvoice()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runReceivableAging", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunReceivableAging")
    @ResponseWrapper(localName = "runReceivableAgingResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunReceivableAgingResponse")
    public void runReceivableAging()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isInvoiceRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsInvoiceRunning")
    @ResponseWrapper(localName = "isInvoiceRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsInvoiceRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
    public java.lang.Boolean isInvoiceRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isPaymentRequestRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsPaymentRequestRunning")
    @ResponseWrapper(localName = "isPaymentRequestRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsPaymentRequestRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
    public java.lang.Boolean isPaymentRequestRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runWorkflow", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunWorkflow")
    @ResponseWrapper(localName = "runWorkflowResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunWorkflowResponse")
    public void runWorkflow()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isCaptureDailyBalancesRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsCaptureDailyBalancesRunning")
    @ResponseWrapper(localName = "isCaptureDailyBalancesRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsCaptureDailyBalancesRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
    public java.lang.Boolean isCaptureDailyBalancesRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runPaymentRequest", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunPaymentRequest")
    @ResponseWrapper(localName = "runPaymentRequestResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunPaymentRequestResponse")
    public void runPaymentRequest()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runInvoiceDue", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunInvoiceDue")
    @ResponseWrapper(localName = "runInvoiceDueResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunInvoiceDueResponse")
    public void runInvoiceDue()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isInvoiceDueRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsInvoiceDueRunning")
    @ResponseWrapper(localName = "isInvoiceDueRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsInvoiceDueRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
    public java.lang.Boolean isInvoiceDueRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isReceivableAgingRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsReceivableAgingRunning")
    @ResponseWrapper(localName = "isReceivableAgingRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsReceivableAgingRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
    public java.lang.Boolean isReceivableAgingRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCurrentDate", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.GetCurrentDate")
    @ResponseWrapper(localName = "getCurrentDateResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.GetCurrentDateResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
    public javax.xml.datatype.XMLGregorianCalendar getCurrentDate()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isWorkflowRunning", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsWorkflowRunning")
    @ResponseWrapper(localName = "isWorkflowRunningResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.IsWorkflowRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
    public java.lang.Boolean isWorkflowRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runCaptureDailyBalances", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunCaptureDailyBalances")
    @ResponseWrapper(localName = "runCaptureDailyBalancesResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.bc.RunCaptureDailyBalancesResponse")
    public void runCaptureDailyBalances()
 throws WsiAuthenticationException_Exception;
}
