
package framework.integrations.gwServices.debugToolsAPI.bc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-05-24T12:55:28.442-06:00
 * Generated source version: 3.4.3
 */

@WebFault(name = "WsiAuthenticationException", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/policycenter/bc1000/BCDebugToolsAPI")
public class WsiAuthenticationException_Exception extends Exception {

    private framework.integrations.gwServices.debugToolsAPI.bc.WsiAuthenticationException faultInfo;

    public WsiAuthenticationException_Exception() {
        super();
    }

    public WsiAuthenticationException_Exception(String message) {
        super(message);
    }

    public WsiAuthenticationException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WsiAuthenticationException_Exception(String message, framework.integrations.gwServices.debugToolsAPI.bc.WsiAuthenticationException wsiAuthenticationException) {
        super(message);
        this.faultInfo = wsiAuthenticationException;
    }

    public WsiAuthenticationException_Exception(String message, framework.integrations.gwServices.debugToolsAPI.bc.WsiAuthenticationException wsiAuthenticationException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = wsiAuthenticationException;
    }

    public framework.integrations.gwServices.debugToolsAPI.bc.WsiAuthenticationException getFaultInfo() {
        return this.faultInfo;
    }
}
