package framework.integrations.gwServices.messagingToolsAPI.cc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-04-09T10:41:08.307-06:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", name = "MessagingToolsAPIPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MessagingToolsAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "retryRetryableErrorMessages", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryRetryableErrorMessages")
    @ResponseWrapper(localName = "retryRetryableErrorMessagesResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryRetryableErrorMessagesResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean retryRetryableErrorMessages(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "suspendDestination", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.SuspendDestination")
    @ResponseWrapper(localName = "suspendDestinationResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.SuspendDestinationResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean suspendDestination(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "direction", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        framework.integrations.gwServices.messagingToolsAPI.cc.MessageProcessingDirection direction
    ) throws IllegalArgumentException_Exception, SOAPException_Exception, SOAPSenderException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTotalStatistics", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetTotalStatistics")
    @ResponseWrapper(localName = "getTotalStatisticsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetTotalStatisticsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public framework.integrations.gwServices.messagingToolsAPI.cc.MessageStatisticsData getTotalStatistics(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "configureDestination", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ConfigureDestination")
    @ResponseWrapper(localName = "configureDestinationResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ConfigureDestinationResponse")
    public void configureDestination(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "timeToWaitInSec", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int timeToWaitInSec,
        @WebParam(name = "maxretries", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.Integer maxretries,
        @WebParam(name = "initialretryinterval", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.Long initialretryinterval,
        @WebParam(name = "retrybackoffmultiplier", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.Integer retrybackoffmultiplier,
        @WebParam(name = "pollinterval", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.Integer pollinterval,
        @WebParam(name = "numsenderthreads", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.Integer numsenderthreads,
        @WebParam(name = "chunksize", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.Integer chunksize
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isSuspended", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.IsSuspended")
    @ResponseWrapper(localName = "isSuspendedResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.IsSuspendedResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean isSuspended(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "direction", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        framework.integrations.gwServices.messagingToolsAPI.cc.MessageProcessingDirection direction
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "retryRetryableSomeErrorMessages", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryRetryableSomeErrorMessages")
    @ResponseWrapper(localName = "retryRetryableSomeErrorMessagesResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryRetryableSomeErrorMessagesResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean retryRetryableSomeErrorMessages(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "retryLimit", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int retryLimit
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "purgeCompletedMessages", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.PurgeCompletedMessages")
    @ResponseWrapper(localName = "purgeCompletedMessagesResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.PurgeCompletedMessagesResponse")
    public void purgeCompletedMessages(

        @WebParam(name = "cutoff", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        javax.xml.datatype.XMLGregorianCalendar cutoff
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "resumeDestination", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ResumeDestination")
    @ResponseWrapper(localName = "resumeDestinationResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ResumeDestinationResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean resumeDestination(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "direction", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        framework.integrations.gwServices.messagingToolsAPI.cc.MessageProcessingDirection direction
    ) throws IllegalArgumentException_Exception, SOAPException_Exception, SOAPSenderException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "skipMessage", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.SkipMessage")
    @ResponseWrapper(localName = "skipMessageResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.SkipMessageResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean skipMessage(

        @WebParam(name = "messageID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        long messageID
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDestinationStatus", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetDestinationStatus")
    @ResponseWrapper(localName = "getDestinationStatusResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetDestinationStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public java.lang.String getDestinationStatus(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessageId", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetMessageId")
    @ResponseWrapper(localName = "getMessageIdResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetMessageIdResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public long getMessageId(

        @WebParam(name = "senderRefID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.String senderRefID,
        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "retryRetryableErrorMessagesForCategory", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryRetryableErrorMessagesForCategory")
    @ResponseWrapper(localName = "retryRetryableErrorMessagesForCategoryResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryRetryableErrorMessagesForCategoryResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean retryRetryableErrorMessagesForCategory(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "category", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.String category
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessageIdBySenderRefId", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetMessageIdBySenderRefId")
    @ResponseWrapper(localName = "getMessageIdBySenderRefIdResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetMessageIdBySenderRefIdResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public java.lang.Long getMessageIdBySenderRefId(

        @WebParam(name = "senderRefID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.String senderRefID,
        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "retryMessage", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryMessage")
    @ResponseWrapper(localName = "retryMessageResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.RetryMessageResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean retryMessage(

        @WebParam(name = "messageID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        long messageID
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isResumed", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.IsResumed")
    @ResponseWrapper(localName = "isResumedResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.IsResumedResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean isResumed(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "direction", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        framework.integrations.gwServices.messagingToolsAPI.cc.MessageProcessingDirection direction
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "resumeDestinationBothDirections", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ResumeDestinationBothDirections")
    @ResponseWrapper(localName = "resumeDestinationBothDirectionsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ResumeDestinationBothDirectionsResponse")
    public void resumeDestinationBothDirections(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "ackMessage", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.AckMessage")
    @ResponseWrapper(localName = "ackMessageResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.AckMessageResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public boolean ackMessage(

        @WebParam(name = "ack", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        framework.integrations.gwServices.messagingToolsAPI.cc.Acknowledgement ack
    ) throws IllegalArgumentException_Exception, SOAPException_Exception, SOAPSenderException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "suspendDestinationBothDirections", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.SuspendDestinationBothDirections")
    @ResponseWrapper(localName = "suspendDestinationBothDirectionsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.SuspendDestinationBothDirectionsResponse")
    public void suspendDestinationBothDirections(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "resyncClaim", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ResyncClaim")
    @ResponseWrapper(localName = "resyncClaimResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.ResyncClaimResponse")
    public void resyncClaim(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "claimID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.String claimID
    ) throws DataConversionException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getConfiguration", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetConfiguration")
    @ResponseWrapper(localName = "getConfigurationResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public framework.integrations.gwServices.messagingToolsAPI.cc.ExternalDestinationConfig getConfiguration(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMessageStatisticsForSafeOrderedObject", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetMessageStatisticsForSafeOrderedObject")
    @ResponseWrapper(localName = "getMessageStatisticsForSafeOrderedObjectResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI", className = "framework.integrations.gwServices.messagingToolsAPI.cc.GetMessageStatisticsForSafeOrderedObjectResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
    public framework.integrations.gwServices.messagingToolsAPI.cc.MessageStatisticsData getMessageStatisticsForSafeOrderedObject(

        @WebParam(name = "destID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        int destID,
        @WebParam(name = "safeOrderedObjectId", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
        java.lang.String safeOrderedObjectId
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;
}
