package framework.integrations.gwServices.maintenanceToolsAPI.cc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-04-09T10:21:49.423-06:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", name = "MaintenanceToolsAPIPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MaintenanceToolsAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "scheduleAggLimitRebuildInvalidLimits", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildInvalidLimits")
    @ResponseWrapper(localName = "scheduleAggLimitRebuildInvalidLimitsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildInvalidLimitsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public java.lang.String scheduleAggLimitRebuildInvalidLimits()
 throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getNumActiveWorkItems", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetNumActiveWorkItems")
    @ResponseWrapper(localName = "getNumActiveWorkItemsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetNumActiveWorkItemsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public int getNumActiveWorkItems(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "changeSubtype", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ChangeSubtype")
    @ResponseWrapper(localName = "changeSubtypeResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ChangeSubtypeResponse")
    public void changeSubtype(

        @WebParam(name = "publicID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String publicID,
        @WebParam(name = "targetType", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String targetType
    ) throws WsiAuthenticationException_Exception, WebServiceException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getValidBatchProcessNames", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetValidBatchProcessNames")
    @ResponseWrapper(localName = "getValidBatchProcessNamesResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetValidBatchProcessNamesResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.GetValidBatchProcessNamesResponse.Return getValidBatchProcessNames()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "notifyQueueWorkers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.NotifyQueueWorkers")
    @ResponseWrapper(localName = "notifyQueueWorkersResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.NotifyQueueWorkersResponse")
    public void notifyQueueWorkers(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "restore", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.Restore")
    @ResponseWrapper(localName = "restoreResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.RestoreResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public java.lang.String restore(

        @WebParam(name = "claimNumbers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.Restore.ClaimNumbers claimNumbers,
        @WebParam(name = "comment", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String comment
    ) throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isBatchProcessNameValid", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.IsBatchProcessNameValid")
    @ResponseWrapper(localName = "isBatchProcessNameValidResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.IsBatchProcessNameValidResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public boolean isBatchProcessNameValid(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startPluginWithTimeout", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartPluginWithTimeout")
    @ResponseWrapper(localName = "startPluginWithTimeoutResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartPluginWithTimeoutResponse")
    public void startPluginWithTimeout(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String pluginName,
        @WebParam(name = "timeout", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        long timeout
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setWorkQueueConfig", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.SetWorkQueueConfig")
    @ResponseWrapper(localName = "setWorkQueueConfigResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.SetWorkQueueConfigResponse")
    public void setWorkQueueConfig(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName,
        @WebParam(name = "config", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.WorkQueueConfig config
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "scheduleAggLimitRebuildOfClaims", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildOfClaims")
    @ResponseWrapper(localName = "scheduleAggLimitRebuildOfClaimsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildOfClaimsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public java.lang.String scheduleAggLimitRebuildOfClaims(

        @WebParam(name = "claimNumbers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildOfClaims.ClaimNumbers claimNumbers
    ) throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "waitOnActiveWorkItems", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.WaitOnActiveWorkItems")
    @ResponseWrapper(localName = "waitOnActiveWorkItemsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.WaitOnActiveWorkItemsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public boolean waitOnActiveWorkItems(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startWorkQueueWorkers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartWorkQueueWorkers")
    @ResponseWrapper(localName = "startWorkQueueWorkersResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartWorkQueueWorkersResponse")
    public void startWorkQueueWorkers(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "scheduleAggLimitRebuildAllLimits", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildAllLimits")
    @ResponseWrapper(localName = "scheduleAggLimitRebuildAllLimitsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildAllLimitsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public java.lang.String scheduleAggLimitRebuildAllLimits()
 throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "markPurgeReady", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.MarkPurgeReady")
    @ResponseWrapper(localName = "markPurgeReadyResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.MarkPurgeReadyResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public java.lang.String markPurgeReady(

        @WebParam(name = "claimNumbers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.MarkPurgeReady.ClaimNumbers claimNumbers,
        @WebParam(name = "purgeFromAggregateLimit", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        boolean purgeFromAggregateLimit
    ) throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "scheduleForArchive", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleForArchive")
    @ResponseWrapper(localName = "scheduleForArchiveResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleForArchiveResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public java.lang.String scheduleForArchive(

        @WebParam(name = "claimNumbers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleForArchive.ClaimNumbers claimNumbers
    ) throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "stopPluginWithTimeout", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StopPluginWithTimeout")
    @ResponseWrapper(localName = "stopPluginWithTimeoutResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StopPluginWithTimeoutResponse")
    public void stopPluginWithTimeout(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String pluginName,
        @WebParam(name = "timeout", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        long timeout
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "requestTerminationOfBatchProcessByID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.RequestTerminationOfBatchProcessByID")
    @ResponseWrapper(localName = "requestTerminationOfBatchProcessByIDResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.RequestTerminationOfBatchProcessByIDResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public boolean requestTerminationOfBatchProcessByID(

        @WebParam(name = "pid", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.ProcessID pid
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWorkQueueConfig", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetWorkQueueConfig")
    @ResponseWrapper(localName = "getWorkQueueConfigResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetWorkQueueConfigResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.WorkQueueConfig getWorkQueueConfig(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "batchProcessStatusByID", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.BatchProcessStatusByID")
    @ResponseWrapper(localName = "batchProcessStatusByIDResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.BatchProcessStatusByIDResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.ProcessStatus batchProcessStatusByID(

        @WebParam(name = "pid", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.ProcessID pid
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "stopPlugin", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StopPlugin")
    @ResponseWrapper(localName = "stopPluginResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StopPluginResponse")
    public void stopPlugin(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String pluginName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startBatchProcessWithArguments", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartBatchProcessWithArguments")
    @ResponseWrapper(localName = "startBatchProcessWithArgumentsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartBatchProcessWithArgumentsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.ProcessID startBatchProcessWithArguments(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String processName,
        @WebParam(name = "arguments", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.StartBatchProcessWithArguments.Arguments arguments
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "stopWorkQueueWorkers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StopWorkQueueWorkers")
    @ResponseWrapper(localName = "stopWorkQueueWorkersResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StopWorkQueueWorkersResponse")
    public void stopWorkQueueWorkers(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "batchProcessStatusByName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.BatchProcessStatusByName")
    @ResponseWrapper(localName = "batchProcessStatusByNameResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.BatchProcessStatusByNameResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.ProcessStatus batchProcessStatusByName(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "whenStatsCalculated", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.WhenStatsCalculated")
    @ResponseWrapper(localName = "whenStatsCalculatedResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.WhenStatsCalculatedResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public javax.xml.datatype.XMLGregorianCalendar whenStatsCalculated()
 throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startPlugin", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartPlugin")
    @ResponseWrapper(localName = "startPluginResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartPluginResponse")
    public void startPlugin(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String pluginName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "requestTerminationOfBatchProcessByName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.RequestTerminationOfBatchProcessByName")
    @ResponseWrapper(localName = "requestTerminationOfBatchProcessByNameResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.RequestTerminationOfBatchProcessByNameResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public boolean requestTerminationOfBatchProcessByName(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "scheduleAggLimitRebuildOfPolicies", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildOfPolicies")
    @ResponseWrapper(localName = "scheduleAggLimitRebuildOfPoliciesResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildOfPoliciesResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public java.lang.String scheduleAggLimitRebuildOfPolicies(

        @WebParam(name = "policyNumbers", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.cc.ScheduleAggLimitRebuildOfPolicies.PolicyNumbers policyNumbers
    ) throws WsiAuthenticationException_Exception, SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWorkQueueNames", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetWorkQueueNames")
    @ResponseWrapper(localName = "getWorkQueueNamesResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetWorkQueueNamesResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.GetWorkQueueNamesResponse.Return getWorkQueueNames()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWQueueStatus", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetWQueueStatus")
    @ResponseWrapper(localName = "getWQueueStatusResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.GetWQueueStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.WQueueStatus getWQueueStatus(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startBatchProcess", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartBatchProcess")
    @ResponseWrapper(localName = "startBatchProcessResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.StartBatchProcessResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.cc.ProcessID startBatchProcess(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isPluginStarted", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.IsPluginStarted")
    @ResponseWrapper(localName = "isPluginStartedResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.cc.IsPluginStartedResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
    public boolean isPluginStarted(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
        java.lang.String pluginName
    ) throws WsiAuthenticationException_Exception, IllegalArgumentException_Exception;
}
