
package framework.integrations.gwServices.maintenanceToolsAPI.cc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-04-09T10:21:49.423-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "WebServiceException", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MaintenanceToolsAPI")
public class WebServiceException_Exception extends Exception {

    private framework.integrations.gwServices.maintenanceToolsAPI.cc.WebServiceException webServiceException;

    public WebServiceException_Exception() {
        super();
    }

    public WebServiceException_Exception(String message) {
        super(message);
    }

    public WebServiceException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WebServiceException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.cc.WebServiceException webServiceException) {
        super(message);
        this.webServiceException = webServiceException;
    }

    public WebServiceException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.cc.WebServiceException webServiceException, java.lang.Throwable cause) {
        super(message, cause);
        this.webServiceException = webServiceException;
    }

    public framework.integrations.gwServices.maintenanceToolsAPI.cc.WebServiceException getFaultInfo() {
        return this.webServiceException;
    }
}
