
package framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi;

import framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.tools.ProcessID;
import framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.ProcessStatus;
import framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.WQueueStatus;
import framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.WorkQueueConfig;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MaintenanceToolsAPIPortType", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
@XmlSeeAlso({
    framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.ObjectFactory.class,
    framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.ObjectFactory.class,
    framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.tools.ObjectFactory.class,
    framework.integrations.gwServices.soapheaders.ObjectFactory.class
})
public interface MaintenanceToolsAPIPortType {


    /**
     * 
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetValidBatchProcessNamesResponse.Return
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "getValidBatchProcessNames", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetValidBatchProcessNames")
    @ResponseWrapper(localName = "getValidBatchProcessNamesResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetValidBatchProcessNamesResponse")
    public framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetValidBatchProcessNamesResponse.Return getValidBatchProcessNames()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param processName
     * @return
     *     returns boolean
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "isBatchProcessNameValid", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.IsBatchProcessNameValid")
    @ResponseWrapper(localName = "isBatchProcessNameValidResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.IsBatchProcessNameValidResponse")
    public boolean isBatchProcessNameValid(
        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String processName)
        throws RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param processName
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.tools.ProcessID
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "startBatchProcess", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartBatchProcess")
    @ResponseWrapper(localName = "startBatchProcessResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartBatchProcessResponse")
    public ProcessID startBatchProcess(
        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String processName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param processName
     * @param productionDate
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.tools.ProcessID
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "startCustomBatchProcess", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartCustomBatchProcess")
    @ResponseWrapper(localName = "startCustomBatchProcessResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartCustomBatchProcessResponse")
    public ProcessID startCustomBatchProcess(
        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String processName,
        @WebParam(name = "productionDate", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        XMLGregorianCalendar productionDate)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.tools.ProcessID
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "startValidateArchiveLinksBatchProcessAll", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartValidateArchiveLinksBatchProcessAll")
    @ResponseWrapper(localName = "startValidateArchiveLinksBatchProcessAllResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartValidateArchiveLinksBatchProcessAllResponse")
    public ProcessID startValidateArchiveLinksBatchProcessAll()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param startTime
     * @param endTime
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.tools.ProcessID
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "startValidateArchiveLinksBatchProcessByDateRange", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartValidateArchiveLinksBatchProcessByDateRange")
    @ResponseWrapper(localName = "startValidateArchiveLinksBatchProcessByDateRangeResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartValidateArchiveLinksBatchProcessByDateRangeResponse")
    public ProcessID startValidateArchiveLinksBatchProcessByDateRange(
        @WebParam(name = "startTime", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        XMLGregorianCalendar endTime)
        throws RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param ids
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.tools.ProcessID
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "startValidateArchiveLinksBatchProcessByIds", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartValidateArchiveLinksBatchProcessByIds")
    @ResponseWrapper(localName = "startValidateArchiveLinksBatchProcessByIdsResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartValidateArchiveLinksBatchProcessByIdsResponse")
    public ProcessID startValidateArchiveLinksBatchProcessByIds(
        @WebParam(name = "ids", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartValidateArchiveLinksBatchProcessByIds.Ids ids)
        throws RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param processName
     * @return
     *     returns boolean
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "requestTerminationOfBatchProcessByName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.RequestTerminationOfBatchProcessByName")
    @ResponseWrapper(localName = "requestTerminationOfBatchProcessByNameResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.RequestTerminationOfBatchProcessByNameResponse")
    public boolean requestTerminationOfBatchProcessByName(
        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String processName)
        throws RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param pid
     * @return
     *     returns boolean
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "requestTerminationOfBatchProcessByID", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.RequestTerminationOfBatchProcessByID")
    @ResponseWrapper(localName = "requestTerminationOfBatchProcessByIDResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.RequestTerminationOfBatchProcessByIDResponse")
    public boolean requestTerminationOfBatchProcessByID(
        @WebParam(name = "pid", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        ProcessID pid)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param processName
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.ProcessStatus
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "batchProcessStatusByName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.BatchProcessStatusByName")
    @ResponseWrapper(localName = "batchProcessStatusByNameResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.BatchProcessStatusByNameResponse")
    public ProcessStatus batchProcessStatusByName(
        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String processName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param pid
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.ProcessStatus
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "batchProcessStatusByID", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.BatchProcessStatusByID")
    @ResponseWrapper(localName = "batchProcessStatusByIDResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.BatchProcessStatusByIDResponse")
    public ProcessStatus batchProcessStatusByID(
        @WebParam(name = "pid", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        ProcessID pid)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "whenStatsCalculated", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.WhenStatsCalculated")
    @ResponseWrapper(localName = "whenStatsCalculatedResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.WhenStatsCalculatedResponse")
    public XMLGregorianCalendar whenStatsCalculated()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param queueName
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.WorkQueueConfig
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "getWorkQueueConfig", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWorkQueueConfig")
    @ResponseWrapper(localName = "getWorkQueueConfigResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWorkQueueConfigResponse")
    public WorkQueueConfig getWorkQueueConfig(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param config
     * @param queueName
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setWorkQueueConfig", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.SetWorkQueueConfig")
    @ResponseWrapper(localName = "setWorkQueueConfigResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.SetWorkQueueConfigResponse")
    public void setWorkQueueConfig(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName,
        @WebParam(name = "config", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        WorkQueueConfig config)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWorkQueueNamesResponse.Return
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "getWorkQueueNames", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWorkQueueNames")
    @ResponseWrapper(localName = "getWorkQueueNamesResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWorkQueueNamesResponse")
    public framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWorkQueueNamesResponse.Return getWorkQueueNames()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param queueName
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "notifyQueueWorkers", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.NotifyQueueWorkers")
    @ResponseWrapper(localName = "notifyQueueWorkersResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.NotifyQueueWorkersResponse")
    public void notifyQueueWorkers(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param queueName
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "stopWorkQueueWorkers", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StopWorkQueueWorkers")
    @ResponseWrapper(localName = "stopWorkQueueWorkersResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StopWorkQueueWorkersResponse")
    public void stopWorkQueueWorkers(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param queueName
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "startWorkQueueWorkers", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartWorkQueueWorkers")
    @ResponseWrapper(localName = "startWorkQueueWorkersResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartWorkQueueWorkersResponse")
    public void startWorkQueueWorkers(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param queueName
     * @return
     *     returns framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.gw.api.webservice.maintenancetools.WQueueStatus
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "getWQueueStatus", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWQueueStatus")
    @ResponseWrapper(localName = "getWQueueStatusResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetWQueueStatusResponse")
    public WQueueStatus getWQueueStatus(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param queueName
     * @return
     *     returns int
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "getNumActiveWorkItems", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetNumActiveWorkItems")
    @ResponseWrapper(localName = "getNumActiveWorkItemsResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.GetNumActiveWorkItemsResponse")
    public int getNumActiveWorkItems(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param queueName
     * @return
     *     returns boolean
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "waitOnActiveWorkItems", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.WaitOnActiveWorkItems")
    @ResponseWrapper(localName = "waitOnActiveWorkItemsResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.WaitOnActiveWorkItemsResponse")
    public boolean waitOnActiveWorkItems(
        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String queueName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param pluginName
     * @return
     *     returns boolean
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
    @RequestWrapper(localName = "isPluginStarted", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.IsPluginStarted")
    @ResponseWrapper(localName = "isPluginStartedResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.IsPluginStartedResponse")
    public boolean isPluginStarted(
        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String pluginName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param pluginName
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "startPlugin", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartPlugin")
    @ResponseWrapper(localName = "startPluginResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StartPluginResponse")
    public void startPlugin(
        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String pluginName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @param pluginName
     * @throws IllegalArgumentException_Exception
     * @throws RequiredFieldException_Exception
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "stopPlugin", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StopPlugin")
    @ResponseWrapper(localName = "stopPluginResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.StopPluginResponse")
    public void stopPlugin(
        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
        String pluginName)
        throws IllegalArgumentException_Exception, RequiredFieldException_Exception, WsiAuthenticationException_Exception
    ;

}
