
package framework.integrations.gwServices.maintenanceToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WsiAuthenticationException", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MaintenanceToolsAPI")
public class WsiAuthenticationException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1395356899572298716L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WsiAuthenticationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WsiAuthenticationException_Exception(String message, WsiAuthenticationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WsiAuthenticationException_Exception(String message, WsiAuthenticationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.guidewire.pc.ws.gw.webservice.pc.pc800.maintenancetoolsapi.WsiAuthenticationException
     */
    public WsiAuthenticationException getFaultInfo() {
        return faultInfo;
    }

}
