
package framework.integrations.gwServices.maintenanceToolsAPI.bc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-05-03T11:44:55.605-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "DataConversionException", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
public class DataConversionException_Exception extends Exception {

    private framework.integrations.gwServices.maintenanceToolsAPI.bc.DataConversionException dataConversionException;

    public DataConversionException_Exception() {
        super();
    }

    public DataConversionException_Exception(String message) {
        super(message);
    }

    public DataConversionException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DataConversionException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.bc.DataConversionException dataConversionException) {
        super(message);
        this.dataConversionException = dataConversionException;
    }

    public DataConversionException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.bc.DataConversionException dataConversionException, java.lang.Throwable cause) {
        super(message, cause);
        this.dataConversionException = dataConversionException;
    }

    public framework.integrations.gwServices.maintenanceToolsAPI.bc.DataConversionException getFaultInfo() {
        return this.dataConversionException;
    }
}
