package framework.integrations.gwServices.maintenanceToolsAPI.bc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-05-03T11:44:55.612-06:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", name = "MaintenanceToolsAPIPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MaintenanceToolsAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "startBatchProcess", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartBatchProcess")
    @ResponseWrapper(localName = "startBatchProcessResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartBatchProcessResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.ProcessID startBatchProcess(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isPluginStarted", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.IsPluginStarted")
    @ResponseWrapper(localName = "isPluginStartedResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.IsPluginStartedResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public boolean isPluginStarted(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String pluginName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "requestTerminationOfBatchProcessByName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.RequestTerminationOfBatchProcessByName")
    @ResponseWrapper(localName = "requestTerminationOfBatchProcessByNameResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.RequestTerminationOfBatchProcessByNameResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public boolean requestTerminationOfBatchProcessByName(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWQueueStatus", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetWQueueStatus")
    @ResponseWrapper(localName = "getWQueueStatusResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetWQueueStatusResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.WQueueStatus getWQueueStatus(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWorkQueueNames", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetWorkQueueNames")
    @ResponseWrapper(localName = "getWorkQueueNamesResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetWorkQueueNamesResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.GetWorkQueueNamesResponse.Return getWorkQueueNames()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "batchProcessStatusByName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.BatchProcessStatusByName")
    @ResponseWrapper(localName = "batchProcessStatusByNameResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.BatchProcessStatusByNameResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.ProcessStatus batchProcessStatusByName(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startPlugin", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartPlugin")
    @ResponseWrapper(localName = "startPluginResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartPluginResponse")
    public void startPlugin(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String pluginName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "stopPlugin", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StopPlugin")
    @ResponseWrapper(localName = "stopPluginResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StopPluginResponse")
    public void stopPlugin(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String pluginName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startBatchProcessWithArguments", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartBatchProcessWithArguments")
    @ResponseWrapper(localName = "startBatchProcessWithArgumentsResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartBatchProcessWithArgumentsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.ProcessID startBatchProcessWithArguments(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String processName,
        @WebParam(name = "arguments", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.bc.StartBatchProcessWithArguments.Arguments arguments
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "importSampleData", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.ImportSampleData")
    @ResponseWrapper(localName = "importSampleDataResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.ImportSampleDataResponse")
    public void importSampleData(

        @WebParam(name = "dataSet", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String dataSet
    ) throws RequiredFieldException_Exception, DataConversionException_Exception, WsiAuthenticationException_Exception, PermissionException_Exception;

    @WebMethod
    @RequestWrapper(localName = "stopWorkQueueWorkers", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StopWorkQueueWorkers")
    @ResponseWrapper(localName = "stopWorkQueueWorkersResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StopWorkQueueWorkersResponse")
    public void stopWorkQueueWorkers(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "requestTerminationOfBatchProcessByID", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.RequestTerminationOfBatchProcessByID")
    @ResponseWrapper(localName = "requestTerminationOfBatchProcessByIDResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.RequestTerminationOfBatchProcessByIDResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public boolean requestTerminationOfBatchProcessByID(

        @WebParam(name = "pid", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.bc.ProcessID pid
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getWorkQueueConfig", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetWorkQueueConfig")
    @ResponseWrapper(localName = "getWorkQueueConfigResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetWorkQueueConfigResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.WorkQueueConfig getWorkQueueConfig(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "batchProcessStatusByID", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.BatchProcessStatusByID")
    @ResponseWrapper(localName = "batchProcessStatusByIDResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.BatchProcessStatusByIDResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.ProcessStatus batchProcessStatusByID(

        @WebParam(name = "pid", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.bc.ProcessID pid
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "stopPluginWithTimeout", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StopPluginWithTimeout")
    @ResponseWrapper(localName = "stopPluginWithTimeoutResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StopPluginWithTimeoutResponse")
    public void stopPluginWithTimeout(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String pluginName,
        @WebParam(name = "timeout", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        long timeout
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "waitOnActiveWorkItems", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.WaitOnActiveWorkItems")
    @ResponseWrapper(localName = "waitOnActiveWorkItemsResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.WaitOnActiveWorkItemsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public boolean waitOnActiveWorkItems(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startWorkQueueWorkers", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartWorkQueueWorkers")
    @ResponseWrapper(localName = "startWorkQueueWorkersResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartWorkQueueWorkersResponse")
    public void startWorkQueueWorkers(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setWorkQueueConfig", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.SetWorkQueueConfig")
    @ResponseWrapper(localName = "setWorkQueueConfigResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.SetWorkQueueConfigResponse")
    public void setWorkQueueConfig(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName,
        @WebParam(name = "config", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        framework.integrations.gwServices.maintenanceToolsAPI.bc.WorkQueueConfig config
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isBatchProcessNameValid", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.IsBatchProcessNameValid")
    @ResponseWrapper(localName = "isBatchProcessNameValidResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.IsBatchProcessNameValidResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public boolean isBatchProcessNameValid(

        @WebParam(name = "processName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String processName
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "startPluginWithTimeout", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartPluginWithTimeout")
    @ResponseWrapper(localName = "startPluginWithTimeoutResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.StartPluginWithTimeoutResponse")
    public void startPluginWithTimeout(

        @WebParam(name = "pluginName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String pluginName,
        @WebParam(name = "timeout", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        long timeout
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getValidBatchProcessNames", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetValidBatchProcessNames")
    @ResponseWrapper(localName = "getValidBatchProcessNamesResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetValidBatchProcessNamesResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public framework.integrations.gwServices.maintenanceToolsAPI.bc.GetValidBatchProcessNamesResponse.Return getValidBatchProcessNames()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "notifyQueueWorkers", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.NotifyQueueWorkers")
    @ResponseWrapper(localName = "notifyQueueWorkersResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.NotifyQueueWorkersResponse")
    public void notifyQueueWorkers(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getNumActiveWorkItems", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetNumActiveWorkItems")
    @ResponseWrapper(localName = "getNumActiveWorkItemsResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.GetNumActiveWorkItemsResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
    public int getNumActiveWorkItems(

        @WebParam(name = "queueName", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
        java.lang.String queueName
    ) throws IllegalArgumentException_Exception, WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "importDefaultSampleData", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.ImportDefaultSampleData")
    @ResponseWrapper(localName = "importDefaultSampleDataResponse", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI", className = "framework.integrations.gwServices.maintenanceToolsAPI.bc.ImportDefaultSampleDataResponse")
    public void importDefaultSampleData()
 throws DataConversionException_Exception, WsiAuthenticationException_Exception, PermissionException_Exception;
}
