
package framework.integrations.gwServices.maintenanceToolsAPI.bc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-05-03T11:44:55.609-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "PermissionException", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
public class PermissionException_Exception extends Exception {

    private framework.integrations.gwServices.maintenanceToolsAPI.bc.PermissionException permissionException;

    public PermissionException_Exception() {
        super();
    }

    public PermissionException_Exception(String message) {
        super(message);
    }

    public PermissionException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PermissionException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.bc.PermissionException permissionException) {
        super(message);
        this.permissionException = permissionException;
    }

    public PermissionException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.bc.PermissionException permissionException, java.lang.Throwable cause) {
        super(message, cause);
        this.permissionException = permissionException;
    }

    public framework.integrations.gwServices.maintenanceToolsAPI.bc.PermissionException getFaultInfo() {
        return this.permissionException;
    }
}
