
package framework.integrations.gwServices.maintenanceToolsAPI.bc.com.guidewire.bc.ws.gw.webservice.bc.maintenancetoolsapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RequiredFieldException", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MaintenanceToolsAPI")
public class RequiredFieldException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -1189419592711506765L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RequiredFieldException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RequiredFieldException_Exception(String message, RequiredFieldException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RequiredFieldException_Exception(String message, RequiredFieldException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.guidewire.bc.ws.gw.webservice.bc.maintenancetoolsapi.RequiredFieldException
     */
    public RequiredFieldException getFaultInfo() {
        return faultInfo;
    }

}
