
package framework.integrations.gwServices.messagingToolsAPI.pc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-06-14T13:59:44.089-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "RequiredFieldException", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc1000/MessagingToolsAPI")
public class RequiredFieldException_Exception extends Exception {

    private framework.integrations.gwServices.messagingToolsAPI.pc.RequiredFieldException requiredFieldException;

    public RequiredFieldException_Exception() {
        super();
    }

    public RequiredFieldException_Exception(String message) {
        super(message);
    }

    public RequiredFieldException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RequiredFieldException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.pc.RequiredFieldException requiredFieldException) {
        super(message);
        this.requiredFieldException = requiredFieldException;
    }

    public RequiredFieldException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.pc.RequiredFieldException requiredFieldException, java.lang.Throwable cause) {
        super(message, cause);
        this.requiredFieldException = requiredFieldException;
    }

    public framework.integrations.gwServices.messagingToolsAPI.pc.RequiredFieldException getFaultInfo() {
        return this.requiredFieldException;
    }
}
