
package framework.integrations.gwServices.messagingToolsAPI.pc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-06-14T13:59:44.085-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "SOAPException", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc1000/MessagingToolsAPI")
public class SOAPException_Exception extends Exception {

    private framework.integrations.gwServices.messagingToolsAPI.pc.SOAPException soapException;

    public SOAPException_Exception() {
        super();
    }

    public SOAPException_Exception(String message) {
        super(message);
    }

    public SOAPException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SOAPException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.pc.SOAPException soapException) {
        super(message);
        this.soapException = soapException;
    }

    public SOAPException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.pc.SOAPException soapException, java.lang.Throwable cause) {
        super(message, cause);
        this.soapException = soapException;
    }

    public framework.integrations.gwServices.messagingToolsAPI.pc.SOAPException getFaultInfo() {
        return this.soapException;
    }
}
