package framework.integrations.gwServices.debugToolsAPI.pc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-05-24T14:25:18.625-06:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", name = "PCDebugToolsAPIPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface PCDebugToolsAPIPortType {

    @WebMethod
    @RequestWrapper(localName = "isWorkflowRunning", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsWorkflowRunning")
    @ResponseWrapper(localName = "isWorkflowRunningResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsWorkflowRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
    public java.lang.Boolean isWorkflowRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getCurrentDate", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.GetCurrentDate")
    @ResponseWrapper(localName = "getCurrentDateResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.GetCurrentDateResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
    public javax.xml.datatype.XMLGregorianCalendar getCurrentDate()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isPrintDocumentsRunning", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsPrintDocumentsRunning")
    @ResponseWrapper(localName = "isPrintDocumentsRunningResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsPrintDocumentsRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
    public java.lang.Boolean isPrintDocumentsRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isCountyOfficeUpdateRunning", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsCountyOfficeUpdateRunning")
    @ResponseWrapper(localName = "isCountyOfficeUpdateRunningResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsCountyOfficeUpdateRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
    public java.lang.Boolean isCountyOfficeUpdateRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runRenewal", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunRenewal")
    @ResponseWrapper(localName = "runRenewalResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunRenewalResponse")
    public void runRenewal()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runWorkFlow", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunWorkFlow")
    @ResponseWrapper(localName = "runWorkFlowResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunWorkFlowResponse")
    public void runWorkFlow()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isMbreQuarterlyRunning", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsMbreQuarterlyRunning")
    @ResponseWrapper(localName = "isMbreQuarterlyRunningResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsMbreQuarterlyRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
    public java.lang.Boolean isMbreQuarterlyRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isMbreMonthlyRunning", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsMbreMonthlyRunning")
    @ResponseWrapper(localName = "isMbreMonthlyRunningResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsMbreMonthlyRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
    public java.lang.Boolean isMbreMonthlyRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runMbreMonthly", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunMbreMonthly")
    @ResponseWrapper(localName = "runMbreMonthlyResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunMbreMonthlyResponse")
    public void runMbreMonthly()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isRenewalRunning", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsRenewalRunning")
    @ResponseWrapper(localName = "isRenewalRunningResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.IsRenewalRunningResponse")
    @WebResult(name = "return", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
    public java.lang.Boolean isRenewalRunning()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runPrintDocuments", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunPrintDocuments")
    @ResponseWrapper(localName = "runPrintDocumentsResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunPrintDocumentsResponse")
    public void runPrintDocuments()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runMbreQuarterly", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunMbreQuarterly")
    @ResponseWrapper(localName = "runMbreQuarterlyResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunMbreQuarterlyResponse")
    public void runMbreQuarterly()
 throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "moveClockTo", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.MoveClockTo")
    @ResponseWrapper(localName = "moveClockToResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.MoveClockToResponse")
    public void moveClockTo(

        @WebParam(name = "date", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "ipaddress", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
        java.lang.String ipaddress
    ) throws WsiAuthenticationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "runCountyOfficeUpdate", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunCountyOfficeUpdate")
    @ResponseWrapper(localName = "runCountyOfficeUpdateResponse", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI", className = "framework.integrations.gwServices.debugToolsAPI.pc.RunCountyOfficeUpdateResponse")
    public void runCountyOfficeUpdate()
 throws WsiAuthenticationException_Exception;
}
