
package framework.integrations.gwServices.debugToolsAPI.pc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-06-01T17:53:30.615-06:00
 * Generated source version: 3.3.4
 *
 */
public final class PCDebugToolsAPIPortType_PCDebugToolsAPISoap12Port_Client {

    private static final QName SERVICE_NAME = new QName("http://guidewire.com/pc/ws/gw/webservice/pc/pc1000/pcdebugtools/PCDebugToolsAPI", "PCDebugToolsAPI");

    private PCDebugToolsAPIPortType_PCDebugToolsAPISoap12Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PCDebugToolsAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PCDebugToolsAPI ss = new PCDebugToolsAPI(wsdlURL, SERVICE_NAME);
        PCDebugToolsAPIPortType port = ss.getPCDebugToolsAPISoap12Port();

        {
        System.out.println("Invoking moveClockTo...");
        javax.xml.datatype.XMLGregorianCalendar _moveClockTo_date = null;
        java.lang.String _moveClockTo_ipaddress = "";
        try {
            port.moveClockTo(_moveClockTo_date, _moveClockTo_ipaddress);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runCountyOfficeUpdate...");
        try {
            port.runCountyOfficeUpdate();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runMbreQuarterly...");
        try {
            port.runMbreQuarterly();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runPrintDocuments...");
        try {
            port.runPrintDocuments();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isRenewalRunning...");
        try {
            java.lang.Boolean _isRenewalRunning__return = port.isRenewalRunning();
            System.out.println("isRenewalRunning.result=" + _isRenewalRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isMbreMonthlyRunning...");
        try {
            java.lang.Boolean _isMbreMonthlyRunning__return = port.isMbreMonthlyRunning();
            System.out.println("isMbreMonthlyRunning.result=" + _isMbreMonthlyRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runMbreMonthly...");
        try {
            port.runMbreMonthly();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runWorkFlow...");
        try {
            port.runWorkFlow();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isMbreQuarterlyRunning...");
        try {
            java.lang.Boolean _isMbreQuarterlyRunning__return = port.isMbreQuarterlyRunning();
            System.out.println("isMbreQuarterlyRunning.result=" + _isMbreQuarterlyRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runRenewal...");
        try {
            port.runRenewal();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isPrintDocumentsRunning...");
        try {
            java.lang.Boolean _isPrintDocumentsRunning__return = port.isPrintDocumentsRunning();
            System.out.println("isPrintDocumentsRunning.result=" + _isPrintDocumentsRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isCountyOfficeUpdateRunning...");
        try {
            java.lang.Boolean _isCountyOfficeUpdateRunning__return = port.isCountyOfficeUpdateRunning();
            System.out.println("isCountyOfficeUpdateRunning.result=" + _isCountyOfficeUpdateRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getCurrentDate...");
        try {
            javax.xml.datatype.XMLGregorianCalendar _getCurrentDate__return = port.getCurrentDate();
            System.out.println("getCurrentDate.result=" + _getCurrentDate__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking isWorkflowRunning...");
        try {
            java.lang.Boolean _isWorkflowRunning__return = port.isWorkflowRunning();
            System.out.println("isWorkflowRunning.result=" + _isWorkflowRunning__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
