
package framework.integrations.gwServices.debugToolsAPI.pc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-05-24T14:25:18.616-06:00
 * Generated source version: 3.4.3
 */

@WebFault(name = "WsiAuthenticationException", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/pcdebugtools/PCDebugToolsAPI")
public class WsiAuthenticationException_Exception extends Exception {

    private framework.integrations.gwServices.debugToolsAPI.pc.WsiAuthenticationException faultInfo;

    public WsiAuthenticationException_Exception() {
        super();
    }

    public WsiAuthenticationException_Exception(String message) {
        super(message);
    }

    public WsiAuthenticationException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WsiAuthenticationException_Exception(String message, framework.integrations.gwServices.debugToolsAPI.pc.WsiAuthenticationException wsiAuthenticationException) {
        super(message);
        this.faultInfo = wsiAuthenticationException;
    }

    public WsiAuthenticationException_Exception(String message, framework.integrations.gwServices.debugToolsAPI.pc.WsiAuthenticationException wsiAuthenticationException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = wsiAuthenticationException;
    }

    public framework.integrations.gwServices.debugToolsAPI.pc.WsiAuthenticationException getFaultInfo() {
        return this.faultInfo;
    }
}
