
package framework.integrations.gwServices.messagingToolsAPI.ab;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-04-09T10:43:18.845-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "DataConversionException", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/MessagingToolsAPI")
public class DataConversionException_Exception extends Exception {

    private framework.integrations.gwServices.messagingToolsAPI.ab.DataConversionException dataConversionException;

    public DataConversionException_Exception() {
        super();
    }

    public DataConversionException_Exception(String message) {
        super(message);
    }

    public DataConversionException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DataConversionException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.ab.DataConversionException dataConversionException) {
        super(message);
        this.dataConversionException = dataConversionException;
    }

    public DataConversionException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.ab.DataConversionException dataConversionException, java.lang.Throwable cause) {
        super(message, cause);
        this.dataConversionException = dataConversionException;
    }

    public framework.integrations.gwServices.messagingToolsAPI.ab.DataConversionException getFaultInfo() {
        return this.dataConversionException;
    }
}
