
package framework.integrations.gwServices.messagingToolsAPI.ab;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-04-09T10:43:18.843-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "IllegalArgumentException", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/MessagingToolsAPI")
public class IllegalArgumentException_Exception extends Exception {

    private framework.integrations.gwServices.messagingToolsAPI.ab.IllegalArgumentException illegalArgumentException;

    public IllegalArgumentException_Exception() {
        super();
    }

    public IllegalArgumentException_Exception(String message) {
        super(message);
    }

    public IllegalArgumentException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IllegalArgumentException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.ab.IllegalArgumentException illegalArgumentException) {
        super(message);
        this.illegalArgumentException = illegalArgumentException;
    }

    public IllegalArgumentException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.ab.IllegalArgumentException illegalArgumentException, java.lang.Throwable cause) {
        super(message, cause);
        this.illegalArgumentException = illegalArgumentException;
    }

    public framework.integrations.gwServices.messagingToolsAPI.ab.IllegalArgumentException getFaultInfo() {
        return this.illegalArgumentException;
    }
}
