
package framework.integrations.gwServices.messagingToolsAPI.ab;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-04-09T10:43:18.855-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "SOAPException", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/MessagingToolsAPI")
public class SOAPException_Exception extends Exception {

    private framework.integrations.gwServices.messagingToolsAPI.ab.SOAPException soapException;

    public SOAPException_Exception() {
        super();
    }

    public SOAPException_Exception(String message) {
        super(message);
    }

    public SOAPException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SOAPException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.ab.SOAPException soapException) {
        super(message);
        this.soapException = soapException;
    }

    public SOAPException_Exception(String message, framework.integrations.gwServices.messagingToolsAPI.ab.SOAPException soapException, java.lang.Throwable cause) {
        super(message, cause);
        this.soapException = soapException;
    }

    public framework.integrations.gwServices.messagingToolsAPI.ab.SOAPException getFaultInfo() {
        return this.soapException;
    }
}
