
package framework.integrations.gwServices.messagingToolsAPI.bc.com.guidewire.bc.ws.gw.webservice.bc.messagingtoolsapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BatchProcessException", targetNamespace = "http://guidewire.com/bc/ws/gw/webservice/bc/MessagingToolsAPI")
public class BatchProcessException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 666312059033221464L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BatchProcessException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BatchProcessException_Exception(String message, BatchProcessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BatchProcessException_Exception(String message, BatchProcessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: framework.integrations.gwServices.messagingToolsAPI.bc.com.guidewire.bc.ws.gw.webservice.bc.messagingtoolsapi.BatchProcessException
     */
    public BatchProcessException getFaultInfo() {
        return faultInfo;
    }

}
