
package framework.integrations.gwServices.maintenanceToolsAPI.ab;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-05-03T11:42:26.552-06:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "WebServiceException", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/MaintenanceToolsAPI")
public class WebServiceException_Exception extends Exception {

    private framework.integrations.gwServices.maintenanceToolsAPI.ab.WebServiceException webServiceException;

    public WebServiceException_Exception() {
        super();
    }

    public WebServiceException_Exception(String message) {
        super(message);
    }

    public WebServiceException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WebServiceException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.ab.WebServiceException webServiceException) {
        super(message);
        this.webServiceException = webServiceException;
    }

    public WebServiceException_Exception(String message, framework.integrations.gwServices.maintenanceToolsAPI.ab.WebServiceException webServiceException, java.lang.Throwable cause) {
        super(message, cause);
        this.webServiceException = webServiceException;
    }

    public framework.integrations.gwServices.maintenanceToolsAPI.ab.WebServiceException getFaultInfo() {
        return this.webServiceException;
    }
}
