
package framework.integrations.gwServices.messagingToolsAPI.cc.com.guidewire.cc.ws.gw.webservice.cc.messagingtoolsapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DataConversionException", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/MessagingToolsAPI")
public class DataConversionException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 7901829785975335802L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DataConversionException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DataConversionException_Exception(String message, DataConversionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DataConversionException_Exception(String message, DataConversionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: framework.integrations.gwServices.messagingToolsAPI.cc.com.guidewire.cc.ws.gw.webservice.cc.messagingtoolsapi.DataConversionException
     */
    public DataConversionException getFaultInfo() {
        return faultInfo;
    }

}
