
package framework.integrations.gwServices.debugToolsAPI.ab;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-06-03T13:44:58.517-06:00
 * Generated source version: 3.3.4
 *
 */
public final class ABDebugToolsAPIPortType_ABDebugToolsAPISoap11Port_Client {

    private static final QName SERVICE_NAME = new QName("http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", "ABDebugToolsAPI");

    private ABDebugToolsAPIPortType_ABDebugToolsAPISoap11Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ABDebugToolsAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ABDebugToolsAPI ss = new ABDebugToolsAPI(wsdlURL, SERVICE_NAME);
        ABDebugToolsAPIPortType port = ss.getABDebugToolsAPISoap11Port();

        {
        System.out.println("Invoking moveClockTo...");
        javax.xml.datatype.XMLGregorianCalendar _moveClockTo_date = null;
        try {
            port.moveClockTo(_moveClockTo_date);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking runMembershipDuesUpdate...");
        try {
            port.runMembershipDuesUpdate();

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getCurrentDate...");
        try {
            javax.xml.datatype.XMLGregorianCalendar _getCurrentDate__return = port.getCurrentDate();
            System.out.println("getCurrentDate.result=" + _getCurrentDate__return);

        } catch (WsiAuthenticationException_Exception e) {
            System.out.println("Expected exception: WsiAuthenticationException has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
