
package framework.integrations.gwServices.debugToolsAPI.ab;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ABDebugToolsAPIPortType", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ABDebugToolsAPIPortType {


    /**
     * 
     * @param date
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "moveClockTo", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.MoveClockTo")
    @ResponseWrapper(localName = "moveClockToResponse", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.MoveClockToResponse")
    public void moveClockTo(
            @WebParam(name = "date", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI")
                    XMLGregorianCalendar date)
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI")
    @RequestWrapper(localName = "getCurrentDate", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.GetCurrentDate")
    @ResponseWrapper(localName = "getCurrentDateResponse", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.GetCurrentDateResponse")
    public XMLGregorianCalendar getCurrentDate()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runMembershipDuesUpdate", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.RunMembershipDuesUpdate")
    @ResponseWrapper(localName = "runMembershipDuesUpdateResponse", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.RunMembershipDuesUpdateResponse")
    public void runMembershipDuesUpdate()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI")
    @RequestWrapper(localName = "isMembershipDuesUpdateRunning", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.IsMembershipDuesUpdateRunning")
    @ResponseWrapper(localName = "isMembershipDuesUpdateRunningResponse", targetNamespace = "http://guidewire.com/ab/ws/gw/webservice/ab/ab1000/abdebugtoolsapi/ABDebugToolsAPI", className = "gwclockservice.abdebugtoolsapi.IsMembershipDuesUpdateRunningResponse")
    public Boolean isMembershipDuesUpdateRunning()
        throws WsiAuthenticationException_Exception
    ;

}
