
package framework.integrations.gwServices.debugToolsAPI.cc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CCDebugToolsAPIPortType", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CCDebugToolsAPIPortType {


    /**
     * 
     * @param date
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "moveClockTo", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.MoveClockTo")
    @ResponseWrapper(localName = "moveClockToResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.MoveClockToResponse")
    public void moveClockTo(
            @WebParam(name = "date", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI")
                    XMLGregorianCalendar date)
        throws WsiAuthenticationException_Exception
    ;

    /**
     *
     * @param days
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addDays", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.AddDays")
    @ResponseWrapper(localName = "addDaysResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.AddDaysResponse")
    public void addDays(
            @WebParam(name = "days", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI")
                    int days)
        throws WsiAuthenticationException_Exception
    ;

    /**
     *
     * @param months
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addMonths", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.AddMonths")
    @ResponseWrapper(localName = "addMonthsResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.AddMonthsResponse")
    public void addMonths(
            @WebParam(name = "months", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI")
                    int months)
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI")
    @RequestWrapper(localName = "getCurrentTime", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.GetCurrentTime")
    @ResponseWrapper(localName = "getCurrentTimeResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.GetCurrentTimeResponse")
    public XMLGregorianCalendar getCurrentTime()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runMainframeOlieCheckFile", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.RunMainframeOlieCheckFile")
    @ResponseWrapper(localName = "runMainframeOlieCheckFileResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.RunMainframeOlieCheckFileResponse")
    public void runMainframeOlieCheckFile()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI")
    @RequestWrapper(localName = "isMainframeOlieCheckFileRunning", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.IsMainframeOlieCheckFileRunning")
    @ResponseWrapper(localName = "isMainframeOlieCheckFileRunningResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.IsMainframeOlieCheckFileRunningResponse")
    public Boolean isMainframeOlieCheckFileRunning()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "runFinancialEsc", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.RunFinancialEsc")
    @ResponseWrapper(localName = "runFinancialEscResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.RunFinancialEscResponse")
    public void runFinancialEsc()
        throws WsiAuthenticationException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     * @throws WsiAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI")
    @RequestWrapper(localName = "isFinancialEscRunning", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.IsFinancialEscRunning")
    @ResponseWrapper(localName = "isFinancialEscRunningResponse", targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc700/ccdebugtools/CCDebugToolsAPI", className = "gwclockservice.ccdebugtoolsapi.IsFinancialEscRunningResponse")
    public Boolean isFinancialEscRunning()
        throws WsiAuthenticationException_Exception
    ;

}
