package framework.integrations.gwServices.debugToolsAPI.cc;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2021-06-03T13:54:41.274-06:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "CCDebugToolsAPI",
                  wsdlLocation = "file:/D:/Work/IntellijProjects/Silicon/src/main/java/framework/integrations/gwServices/debugToolsAPI/cc/CCDebugToolsAPI.wsdl",
                  targetNamespace = "http://guidewire.com/cc/ws/gw/webservice/cc/cc1000/ccdebugtools/CCDebugToolsAPI")
public class CCDebugToolsAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc1000/ccdebugtools/CCDebugToolsAPI", "CCDebugToolsAPI");
    public final static QName CCDebugToolsAPISoap11Port = new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc1000/ccdebugtools/CCDebugToolsAPI", "CCDebugToolsAPISoap11Port");
    public final static QName CCDebugToolsAPISoap12Port = new QName("http://guidewire.com/cc/ws/gw/webservice/cc/cc1000/ccdebugtools/CCDebugToolsAPI", "CCDebugToolsAPISoap12Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Work/IntellijProjects/Silicon/src/main/java/framework/integrations/gwServices/debugToolsAPI/cc/CCDebugToolsAPI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CCDebugToolsAPI.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Work/IntellijProjects/Silicon/src/main/java/framework/integrations/gwServices/debugToolsAPI/cc/CCDebugToolsAPI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CCDebugToolsAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CCDebugToolsAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCDebugToolsAPI() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CCDebugToolsAPI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CCDebugToolsAPI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CCDebugToolsAPI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CCDebugToolsAPIPortType
     */
    @WebEndpoint(name = "CCDebugToolsAPISoap11Port")
    public CCDebugToolsAPIPortType getCCDebugToolsAPISoap11Port() {
        return super.getPort(CCDebugToolsAPISoap11Port, CCDebugToolsAPIPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCDebugToolsAPIPortType
     */
    @WebEndpoint(name = "CCDebugToolsAPISoap11Port")
    public CCDebugToolsAPIPortType getCCDebugToolsAPISoap11Port(WebServiceFeature... features) {
        return super.getPort(CCDebugToolsAPISoap11Port, CCDebugToolsAPIPortType.class, features);
    }


    /**
     *
     * @return
     *     returns CCDebugToolsAPIPortType
     */
    @WebEndpoint(name = "CCDebugToolsAPISoap12Port")
    public CCDebugToolsAPIPortType getCCDebugToolsAPISoap12Port() {
        return super.getPort(CCDebugToolsAPISoap12Port, CCDebugToolsAPIPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCDebugToolsAPIPortType
     */
    @WebEndpoint(name = "CCDebugToolsAPISoap12Port")
    public CCDebugToolsAPIPortType getCCDebugToolsAPISoap12Port(WebServiceFeature... features) {
        return super.getPort(CCDebugToolsAPISoap12Port, CCDebugToolsAPIPortType.class, features);
    }

}
