
package framework.integrations.gwServices.messagingToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.messagingtoolsapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RequiredFieldException", targetNamespace = "http://guidewire.com/pc/ws/gw/webservice/pc/pc800/MessagingToolsAPI")
public class RequiredFieldException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = -7847222152783005349L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RequiredFieldException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RequiredFieldException_Exception(String message, RequiredFieldException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RequiredFieldException_Exception(String message, RequiredFieldException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: framework.integrations.gwServices.messagingToolsAPI.pc.com.guidewire.pc.ws.gw.webservice.pc.pc800.messagingtoolsapi.RequiredFieldException
     */
    public RequiredFieldException getFaultInfo() {
        return faultInfo;
    }

}
